openapi: "3.0.0"
info:
  version: "1.0.0"
  title: 'API CartService'
  description: API for working with cart
servers:
  - url: http://localhost:8083
    description: Cart service
paths:
  /add_item:
    post:
      summary: Add item to cart
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/AddItemRequest"
      responses:
        "200":
          description: Added item to cart
        "400":
          description: Some of parameters missing
        "401":
          description: Cannot authenticate
        "500":
          description: Unexpected error
  /get_cart:
    get:
      summary: Get items from cart
      parameters:
        - name: user_id
          description: User's id
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Get items from cart
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "401":
          description: Cannot authenticate
        "500":
          description: Unexpected error
components:
  schemas:
    Cart:
      type: array
      items:
        $ref: "#/components/schemas/CartEntry"
    CartEntry:
      type: object
      required:
        - product_id
        - quantity
      properties:
        product_id:
          type: integer
        quantity:
          type: integer
    AddItemRequest:
      type: object
      required:
        - user_id
        - product_id
        - quantity
      properties:
        user_id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
